# fly.toml app configuration file generated for joseiz-cms on 2023-09-28T13:11:47-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "joseiz-cms"
primary_region = "mia"

[build]

[env]
  PORT = "1337"

[http_service]
  internal_port = 1337
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
  protocol = "tcp"
