// Interface automatically generated by schemas-to-ts

import { LinkedEntity } from '../../../linked-entity/content-types/linked-entity/linked-entity';
import { Project } from '../../../project/content-types/project/project';
import { LinkedEntity_Plain } from '../../../linked-entity/content-types/linked-entity/linked-entity';
import { Project_Plain } from '../../../project/content-types/project/project';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export enum EmploymentType {
  FullTime = 'Full-time',
  PartTime = 'Part-time',
  Contract = 'Contract',
  Freelance = 'Freelance',
  Internship = 'Internship',
  Temporary = 'Temporary',}
export enum JobModality {
  Remote = 'Remote',
  Hybrid = 'Hybrid',
  OnSite = 'On-site',}

export interface WorkExperience {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    company?: { data: LinkedEntity };
    title?: string;
    description?: string;
    employmentType?: EmploymentType;
    jobModality?: JobModality;
    startDate?: Date;
    endDate?: Date;
    relatedProjects: { data: Project[] };
    inProgress?: boolean;
    onPortfolio?: boolean;
    onCv?: boolean;
    jobLocation?: any;
    locale: string;
    localizations?: { data: WorkExperience[] };
  };
}
export interface WorkExperience_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  company?: LinkedEntity_Plain;
  title?: string;
  description?: string;
  employmentType?: EmploymentType;
  jobModality?: JobModality;
  startDate?: Date;
  endDate?: Date;
  relatedProjects: Project_Plain[];
  inProgress?: boolean;
  onPortfolio?: boolean;
  onCv?: boolean;
  jobLocation?: any;
  locale: string;
  localizations?: WorkExperience[];
}

export interface WorkExperience_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  company?: number;
  title?: string;
  description?: string;
  employmentType?: EmploymentType;
  jobModality?: JobModality;
  startDate?: Date;
  endDate?: Date;
  relatedProjects: number[];
  inProgress?: boolean;
  onPortfolio?: boolean;
  onCv?: boolean;
  jobLocation?: any;
  locale: string;
  localizations?: WorkExperience[];
}

export interface WorkExperience_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  company?: AdminPanelRelationPropertyModification<LinkedEntity_Plain>;
  title?: string;
  description?: string;
  employmentType?: EmploymentType;
  jobModality?: JobModality;
  startDate?: Date;
  endDate?: Date;
  relatedProjects: AdminPanelRelationPropertyModification<Project_Plain>;
  inProgress?: boolean;
  onPortfolio?: boolean;
  onCv?: boolean;
  jobLocation?: any;
  locale: string;
  localizations?: WorkExperience[];
}
