// Interface automatically generated by schemas-to-ts

import { LinkedEntity } from '../../../linked-entity/content-types/linked-entity/linked-entity';
import { Project } from '../../../project/content-types/project/project';
import { EmploymentCategory } from '../../../employment-category/content-types/employment-category/employment-category';
import { ModalityCategory } from '../../../modality-category/content-types/modality-category/modality-category';
import { LinkedEntity_Plain } from '../../../linked-entity/content-types/linked-entity/linked-entity';
import { Project_Plain } from '../../../project/content-types/project/project';
import { EmploymentCategory_Plain } from '../../../employment-category/content-types/employment-category/employment-category';
import { ModalityCategory_Plain } from '../../../modality-category/content-types/modality-category/modality-category';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export interface WorkExperience {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    company?: { data: LinkedEntity };
    title?: string;
    description?: string;
    startDate?: Date;
    endDate?: Date;
    relatedProjects: { data: Project[] };
    inProgress?: boolean;
    onPortfolio?: boolean;
    onCv?: boolean;
    jobLocation?: any;
    employmentType?: { data: EmploymentCategory };
    modality?: { data: ModalityCategory };
    locale: string;
    localizations?: { data: WorkExperience[] };
  };
}
export interface WorkExperience_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  company?: LinkedEntity_Plain;
  title?: string;
  description?: string;
  startDate?: Date;
  endDate?: Date;
  relatedProjects: Project_Plain[];
  inProgress?: boolean;
  onPortfolio?: boolean;
  onCv?: boolean;
  jobLocation?: any;
  employmentType?: EmploymentCategory_Plain;
  modality?: ModalityCategory_Plain;
  locale: string;
  localizations?: WorkExperience[];
}

export interface WorkExperience_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  company?: number;
  title?: string;
  description?: string;
  startDate?: Date;
  endDate?: Date;
  relatedProjects: number[];
  inProgress?: boolean;
  onPortfolio?: boolean;
  onCv?: boolean;
  jobLocation?: any;
  employmentType?: number;
  modality?: number;
  locale: string;
  localizations?: WorkExperience[];
}

export interface WorkExperience_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  company?: AdminPanelRelationPropertyModification<LinkedEntity_Plain>;
  title?: string;
  description?: string;
  startDate?: Date;
  endDate?: Date;
  relatedProjects: AdminPanelRelationPropertyModification<Project_Plain>;
  inProgress?: boolean;
  onPortfolio?: boolean;
  onCv?: boolean;
  jobLocation?: any;
  employmentType?: AdminPanelRelationPropertyModification<EmploymentCategory_Plain>;
  modality?: AdminPanelRelationPropertyModification<ModalityCategory_Plain>;
  locale: string;
  localizations?: WorkExperience[];
}
