// Interface automatically generated by schemas-to-ts

import { Media } from '../../../../common/schemas-to-ts/Media';
import { Language } from '../../../language/content-types/language/language';
import { WebLink } from '../../../web-link/content-types/web-link/web-link';
import { Activity } from '../../../activity/content-types/activity/activity';
import { Achievement } from '../../../achievement/content-types/achievement/achievement';
import { Education } from '../../../education/content-types/education/education';
import { WorkExperience } from '../../../work-experience/content-types/work-experience/work-experience';
import { Project } from '../../../project/content-types/project/project';
import { LinkedEntity } from '../../../linked-entity/content-types/linked-entity/linked-entity';
import { Language_Plain } from '../../../language/content-types/language/language';
import { WebLink_Plain } from '../../../web-link/content-types/web-link/web-link';
import { Activity_Plain } from '../../../activity/content-types/activity/activity';
import { Achievement_Plain } from '../../../achievement/content-types/achievement/achievement';
import { Education_Plain } from '../../../education/content-types/education/education';
import { WorkExperience_Plain } from '../../../work-experience/content-types/work-experience/work-experience';
import { Project_Plain } from '../../../project/content-types/project/project';
import { LinkedEntity_Plain } from '../../../linked-entity/content-types/linked-entity/linked-entity';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export interface GeneralInfo {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    firstName?: string;
    lastName?: string;
    shortSubtitle?: string;
    email?: string;
    phoneNumber?: string;
    profilePhoto?: { data: Media };
    backgroundPhoto?: { data: Media };
    cvDocument?: string;
    aboutMe?: string;
    languages: { data: Language[] };
    webLinks: { data: WebLink[] };
    hobbies: { data: Activity[] };
    softSkills: { data: Activity[] };
    location?: any;
    achievements: { data: Achievement[] };
    educations: { data: Education[] };
    workExperiences: { data: WorkExperience[] };
    projects: { data: Project[] };
    skills: { data: LinkedEntity[] };
    hardSkills: { data: Activity[] };
    locale: string;
    localizations?: { data: GeneralInfo[] };
  };
}
export interface GeneralInfo_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  firstName?: string;
  lastName?: string;
  shortSubtitle?: string;
  email?: string;
  phoneNumber?: string;
  profilePhoto?: Media;
  backgroundPhoto?: Media;
  cvDocument?: string;
  aboutMe?: string;
  languages: Language_Plain[];
  webLinks: WebLink_Plain[];
  hobbies: Activity_Plain[];
  softSkills: Activity_Plain[];
  location?: any;
  achievements: Achievement_Plain[];
  educations: Education_Plain[];
  workExperiences: WorkExperience_Plain[];
  projects: Project_Plain[];
  skills: LinkedEntity_Plain[];
  hardSkills: Activity_Plain[];
  locale: string;
  localizations?: GeneralInfo[];
}

export interface GeneralInfo_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  firstName?: string;
  lastName?: string;
  shortSubtitle?: string;
  email?: string;
  phoneNumber?: string;
  profilePhoto?: number;
  backgroundPhoto?: number;
  cvDocument?: string;
  aboutMe?: string;
  languages: number[];
  webLinks: number[];
  hobbies: number[];
  softSkills: number[];
  location?: any;
  achievements: number[];
  educations: number[];
  workExperiences: number[];
  projects: number[];
  skills: number[];
  hardSkills: number[];
  locale: string;
  localizations?: GeneralInfo[];
}

export interface GeneralInfo_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  firstName?: string;
  lastName?: string;
  shortSubtitle?: string;
  email?: string;
  phoneNumber?: string;
  profilePhoto?: AdminPanelRelationPropertyModification<Media>;
  backgroundPhoto?: AdminPanelRelationPropertyModification<Media>;
  cvDocument?: string;
  aboutMe?: string;
  languages: AdminPanelRelationPropertyModification<Language_Plain>;
  webLinks: AdminPanelRelationPropertyModification<WebLink_Plain>;
  hobbies: AdminPanelRelationPropertyModification<Activity_Plain>;
  softSkills: AdminPanelRelationPropertyModification<Activity_Plain>;
  location?: any;
  achievements: AdminPanelRelationPropertyModification<Achievement_Plain>;
  educations: AdminPanelRelationPropertyModification<Education_Plain>;
  workExperiences: AdminPanelRelationPropertyModification<WorkExperience_Plain>;
  projects: AdminPanelRelationPropertyModification<Project_Plain>;
  skills: AdminPanelRelationPropertyModification<LinkedEntity_Plain>;
  hardSkills: AdminPanelRelationPropertyModification<Activity_Plain>;
  locale: string;
  localizations?: GeneralInfo[];
}
