// Interface automatically generated by schemas-to-ts

import { Media } from '../../../../common/schemas-to-ts/Media';
import { Language } from '../../../language/content-types/language/language';
import { WebLink } from '../../../web-link/content-types/web-link/web-link';
import { Activity } from '../../../activity/content-types/activity/activity';
import { Language_Plain } from '../../../language/content-types/language/language';
import { WebLink_Plain } from '../../../web-link/content-types/web-link/web-link';
import { Activity_Plain } from '../../../activity/content-types/activity/activity';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export interface GeneralInfo {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    firstName?: string;
    lastName?: string;
    shortSubtitle?: string;
    email?: string;
    phoneNumber?: string;
    profilePhoto?: { data: Media };
    backgroundPhoto?: { data: Media };
    cvDocument?: string;
    aboutMe?: string;
    languages: { data: Language[] };
    webLinks: { data: WebLink[] };
    hobbies: { data: Activity[] };
    softSkills: { data: Activity[] };
    location?: any;
    locale: string;
    localizations?: { data: GeneralInfo[] };
  };
}
export interface GeneralInfo_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  firstName?: string;
  lastName?: string;
  shortSubtitle?: string;
  email?: string;
  phoneNumber?: string;
  profilePhoto?: Media;
  backgroundPhoto?: Media;
  cvDocument?: string;
  aboutMe?: string;
  languages: Language_Plain[];
  webLinks: WebLink_Plain[];
  hobbies: Activity_Plain[];
  softSkills: Activity_Plain[];
  location?: any;
  locale: string;
  localizations?: GeneralInfo[];
}

export interface GeneralInfo_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  firstName?: string;
  lastName?: string;
  shortSubtitle?: string;
  email?: string;
  phoneNumber?: string;
  profilePhoto?: number;
  backgroundPhoto?: number;
  cvDocument?: string;
  aboutMe?: string;
  languages: number[];
  webLinks: number[];
  hobbies: number[];
  softSkills: number[];
  location?: any;
  locale: string;
  localizations?: GeneralInfo[];
}

export interface GeneralInfo_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  firstName?: string;
  lastName?: string;
  shortSubtitle?: string;
  email?: string;
  phoneNumber?: string;
  profilePhoto?: AdminPanelRelationPropertyModification<Media>;
  backgroundPhoto?: AdminPanelRelationPropertyModification<Media>;
  cvDocument?: string;
  aboutMe?: string;
  languages: AdminPanelRelationPropertyModification<Language_Plain>;
  webLinks: AdminPanelRelationPropertyModification<WebLink_Plain>;
  hobbies: AdminPanelRelationPropertyModification<Activity_Plain>;
  softSkills: AdminPanelRelationPropertyModification<Activity_Plain>;
  location?: any;
  locale: string;
  localizations?: GeneralInfo[];
}
