// Interface automatically generated by schemas-to-ts

import { LinkedEntity } from '../../../linked-entity/content-types/linked-entity/linked-entity';
import { Media } from '../../../../common/schemas-to-ts/Media';
import { WebLink } from '../../../web-link/content-types/web-link/web-link';
import { LinkedEntity_Plain } from '../../../linked-entity/content-types/linked-entity/linked-entity';
import { WebLink_Plain } from '../../../web-link/content-types/web-link/web-link';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export enum AchievementType {
  Award = 'Award',
  Certificate = 'Certificate',
  Degree = 'Degree',
  Diplom = 'Diplom',}
export enum Modality {
  Remote = 'Remote',
  Hybrid = 'Hybrid',
  OnSite = 'On-site',}

export interface Achievement {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    title?: string;
    institution?: { data: LinkedEntity };
    achievementType?: AchievementType;
    modality?: Modality;
    startDate?: Date;
    endDate?: Date;
    certificateImage?: { data: Media };
    achievementLogo?: { data: Media };
    shortDescription?: string;
    description?: string;
    validationLink?: { data: WebLink };
    noExpiration?: boolean;
    onPortfolio?: boolean;
    onCv?: boolean;
    achieveLocation?: any;
    locale: string;
    localizations?: { data: Achievement[] };
  };
}
export interface Achievement_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title?: string;
  institution?: LinkedEntity_Plain;
  achievementType?: AchievementType;
  modality?: Modality;
  startDate?: Date;
  endDate?: Date;
  certificateImage?: Media;
  achievementLogo?: Media;
  shortDescription?: string;
  description?: string;
  validationLink?: WebLink_Plain;
  noExpiration?: boolean;
  onPortfolio?: boolean;
  onCv?: boolean;
  achieveLocation?: any;
  locale: string;
  localizations?: Achievement[];
}

export interface Achievement_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title?: string;
  institution?: number;
  achievementType?: AchievementType;
  modality?: Modality;
  startDate?: Date;
  endDate?: Date;
  certificateImage?: number;
  achievementLogo?: number;
  shortDescription?: string;
  description?: string;
  validationLink?: number;
  noExpiration?: boolean;
  onPortfolio?: boolean;
  onCv?: boolean;
  achieveLocation?: any;
  locale: string;
  localizations?: Achievement[];
}

export interface Achievement_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title?: string;
  institution?: AdminPanelRelationPropertyModification<LinkedEntity_Plain>;
  achievementType?: AchievementType;
  modality?: Modality;
  startDate?: Date;
  endDate?: Date;
  certificateImage?: AdminPanelRelationPropertyModification<Media>;
  achievementLogo?: AdminPanelRelationPropertyModification<Media>;
  shortDescription?: string;
  description?: string;
  validationLink?: AdminPanelRelationPropertyModification<WebLink_Plain>;
  noExpiration?: boolean;
  onPortfolio?: boolean;
  onCv?: boolean;
  achieveLocation?: any;
  locale: string;
  localizations?: Achievement[];
}
