// Interface automatically generated by schemas-to-ts

import { LinkedEntity } from '../../../linked-entity/content-types/linked-entity/linked-entity';
import { LinkedEntity_Plain } from '../../../linked-entity/content-types/linked-entity/linked-entity';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export enum Category {
  Programming = 'Programming',
  WebDevelopment = 'Web Development',
  BackendDevelopment = 'Backend Development',
  Database = 'Database',
  Design = 'Design',
  TestingFrameworks = 'Testing Frameworks',
  Containerization = 'Containerization',}

export interface Skill {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    linked_entity?: { data: LinkedEntity };
    category?: Category;
    onPortfolio?: boolean;
    onCv?: boolean;
    locale: string;
    localizations?: { data: Skill[] };
  };
}
export interface Skill_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  linked_entity?: LinkedEntity_Plain;
  category?: Category;
  onPortfolio?: boolean;
  onCv?: boolean;
  locale: string;
  localizations?: Skill[];
}

export interface Skill_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  linked_entity?: number;
  category?: Category;
  onPortfolio?: boolean;
  onCv?: boolean;
  locale: string;
  localizations?: Skill[];
}

export interface Skill_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  linked_entity?: AdminPanelRelationPropertyModification<LinkedEntity_Plain>;
  category?: Category;
  onPortfolio?: boolean;
  onCv?: boolean;
  locale: string;
  localizations?: Skill[];
}
