// Interface automatically generated by schemas-to-ts

import { LinkedEntity } from '../../../linked-entity/content-types/linked-entity/linked-entity';
import { CategoryName } from '../../../category-name/content-types/category-name/category-name';
import { LinkedEntity_Plain } from '../../../linked-entity/content-types/linked-entity/linked-entity';
import { CategoryName_Plain } from '../../../category-name/content-types/category-name/category-name';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export interface Skill {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    linked_entity?: { data: LinkedEntity };
    onPortfolio?: boolean;
    onCv?: boolean;
    category?: { data: CategoryName };
    locale: string;
    localizations?: { data: Skill[] };
  };
}
export interface Skill_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  linked_entity?: LinkedEntity_Plain;
  onPortfolio?: boolean;
  onCv?: boolean;
  category?: CategoryName_Plain;
  locale: string;
  localizations?: Skill[];
}

export interface Skill_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  linked_entity?: number;
  onPortfolio?: boolean;
  onCv?: boolean;
  category?: number;
  locale: string;
  localizations?: Skill[];
}

export interface Skill_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  linked_entity?: AdminPanelRelationPropertyModification<LinkedEntity_Plain>;
  onPortfolio?: boolean;
  onCv?: boolean;
  category?: AdminPanelRelationPropertyModification<CategoryName_Plain>;
  locale: string;
  localizations?: Skill[];
}
