// Interface automatically generated by schemas-to-ts

export interface Activity {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    iconName?: string;
    label?: string;
    onPortfolio?: boolean;
    onCv?: boolean;
    locale: string;
    localizations?: { data: Activity[] };
  };
}
export interface Activity_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  iconName?: string;
  label?: string;
  onPortfolio?: boolean;
  onCv?: boolean;
  locale: string;
  localizations?: Activity[];
}

export interface Activity_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  iconName?: string;
  label?: string;
  onPortfolio?: boolean;
  onCv?: boolean;
  locale: string;
  localizations?: Activity[];
}

export interface Activity_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  iconName?: string;
  label?: string;
  onPortfolio?: boolean;
  onCv?: boolean;
  locale: string;
  localizations?: Activity[];
}
