// Interface automatically generated by schemas-to-ts

import { LinkedEntity } from '../../../linked-entity/content-types/linked-entity/linked-entity';
import { LinkedEntity_Plain } from '../../../linked-entity/content-types/linked-entity/linked-entity';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export interface WebLink {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    linked_entity?: { data: LinkedEntity };
    label?: string;
    url: string;
    locale: string;
    localizations?: { data: WebLink[] };
  };
}
export interface WebLink_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  linked_entity?: LinkedEntity_Plain;
  label?: string;
  url: string;
  locale: string;
  localizations?: WebLink[];
}

export interface WebLink_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  linked_entity?: number;
  label?: string;
  url: string;
  locale: string;
  localizations?: WebLink[];
}

export interface WebLink_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  linked_entity?: AdminPanelRelationPropertyModification<LinkedEntity_Plain>;
  label?: string;
  url: string;
  locale: string;
  localizations?: WebLink[];
}
