// Interface automatically generated by schemas-to-ts

import { Media } from '../../../../common/schemas-to-ts/Media';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export interface LinkedEntity {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    name?: string;
    description?: string;
    shortDescription?: string;
    website?: string;
    iconName?: string;
    negativeIconName?: string;
    primaryImage?: { data: Media };
    secondaryImage?: { data: Media };
    slug?: string;
    locale: string;
    localizations?: { data: LinkedEntity[] };
  };
}
export interface LinkedEntity_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  name?: string;
  description?: string;
  shortDescription?: string;
  website?: string;
  iconName?: string;
  negativeIconName?: string;
  primaryImage?: Media;
  secondaryImage?: Media;
  slug?: string;
  locale: string;
  localizations?: LinkedEntity[];
}

export interface LinkedEntity_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  name?: string;
  description?: string;
  shortDescription?: string;
  website?: string;
  iconName?: string;
  negativeIconName?: string;
  primaryImage?: number;
  secondaryImage?: number;
  slug?: string;
  locale: string;
  localizations?: LinkedEntity[];
}

export interface LinkedEntity_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  name?: string;
  description?: string;
  shortDescription?: string;
  website?: string;
  iconName?: string;
  negativeIconName?: string;
  primaryImage?: AdminPanelRelationPropertyModification<Media>;
  secondaryImage?: AdminPanelRelationPropertyModification<Media>;
  slug?: string;
  locale: string;
  localizations?: LinkedEntity[];
}
