// Interface automatically generated by schemas-to-ts

import { Media } from '../../../../common/schemas-to-ts/Media';
import { Project } from '../../../project/content-types/project/project';
import { CategoryName } from '../../../category-name/content-types/category-name/category-name';
import { Project_Plain } from '../../../project/content-types/project/project';
import { CategoryName_Plain } from '../../../category-name/content-types/category-name/category-name';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export interface LinkedEntity {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    name?: string;
    description?: string;
    shortDescription?: string;
    website?: string;
    iconName?: string;
    negativeIconName?: string;
    primaryImage?: { data: Media };
    secondaryImage?: { data: Media };
    slug?: string;
    projects?: { data: Project[] };
    playAsSkill?: boolean;
    onPortfolio?: boolean;
    onCV?: boolean;
    skillCategory?: { data: CategoryName };
    locale: string;
    localizations?: { data: LinkedEntity[] };
  };
}
export interface LinkedEntity_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  name?: string;
  description?: string;
  shortDescription?: string;
  website?: string;
  iconName?: string;
  negativeIconName?: string;
  primaryImage?: Media;
  secondaryImage?: Media;
  slug?: string;
  projects?: Project_Plain[];
  playAsSkill?: boolean;
  onPortfolio?: boolean;
  onCV?: boolean;
  skillCategory?: CategoryName_Plain;
  locale: string;
  localizations?: LinkedEntity[];
}

export interface LinkedEntity_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  name?: string;
  description?: string;
  shortDescription?: string;
  website?: string;
  iconName?: string;
  negativeIconName?: string;
  primaryImage?: number;
  secondaryImage?: number;
  slug?: string;
  projects?: number[];
  playAsSkill?: boolean;
  onPortfolio?: boolean;
  onCV?: boolean;
  skillCategory?: number;
  locale: string;
  localizations?: LinkedEntity[];
}

export interface LinkedEntity_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  name?: string;
  description?: string;
  shortDescription?: string;
  website?: string;
  iconName?: string;
  negativeIconName?: string;
  primaryImage?: AdminPanelRelationPropertyModification<Media>;
  secondaryImage?: AdminPanelRelationPropertyModification<Media>;
  slug?: string;
  projects?: AdminPanelRelationPropertyModification<Project_Plain>;
  playAsSkill?: boolean;
  onPortfolio?: boolean;
  onCV?: boolean;
  skillCategory?: AdminPanelRelationPropertyModification<CategoryName_Plain>;
  locale: string;
  localizations?: LinkedEntity[];
}
